#!/usr/bin/env ruby
# coding: utf-8

url         'http://hibariya.github.com/'
title       'Joy Luck Crab'
description '歓喜 幸福 象さん'
author      'hibariya'

after :edit do
  preview if yes?("Preview now? [yes/no]")
end

after :rebind, :commit

after :commit do
  if yes?("Deploy now? [yes/no]")
    system "cd #{config.retter_home}"
    system 'git push origin master'
  end

  if yes?("Bookmark now? [yes/no]")
    a = Mechanize.new
    login_hatena(a)

    host = URI.parse(config.url).host
    #entries = git.commits.first.diffs.select {|d| d.new_file && d.b_path =~ %r{entries/} }.map(&:b_path)
    entries = git.commits.first.diffs.select {|d| d.b_path =~ %r{entries/} }.map(&:b_path)

    entries.each do |entry|
      a.get("http://b.hatena.ne.jp/entry/#{host}/#{entry}")
      a.page.form_with(name: 'addBookmarkForm', &:click_buttom)
    end
  end
end

def login_hatena(agent)
  STDOUT.sync = true
  agent.get('https://www.hatena.ne.jp/login')

  form = agent.page.forms.first
  form.field_with(name: 'name').value username_prompt
  form.field_with(name: 'password').value password_prompt
  form.click_button
end

def username_prompt
  print 'Username: '
  STDIN.gets.strip
end

def password_prompt
  print 'Password: '

  system "stty -echo"
  password =  STDIN.gets.strip
  system "stty echo"

  password
end
