#!/usr/bin/env ruby
# coding: utf-8

url         'http://hibariya.github.com/'
title       'Joy Luck Crab'
description '歓喜 幸福 象さん'
author      'hibariya'

after :edit do
  preview if yes?("Preview now? [yes/no]")
end

after :rebind, :commit

after :commit do
  if yes?("Deploy now? [yes/no]")
    system "cd #{config.retter_home}"
    system 'git push origin master'
  end
end
